// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlesvlxsynfvxffwmnxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZXN2bHhzeW5mdnhmZndtbnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODc0MzYsImV4cCI6MjA3MjM2MzQzNn0.7ZuJq_1Xh4EVYubKVyqJdpsTTRQqGyd4W99XYcHfWOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});